### ISSUE TITLE
--no-warn-rwx-segments breaks the build on most versions of GCC

### ISSUE THREAD

**Issue by catphish** [jsphuebner/stm32-sine#24]
I understand --no-warn-rwx-segments is useful to suppress a warning on GCC 12+, but on older versions (including the CI tests on Github) it causes the build to fail because the option does not exist :(
Since I don't have GCC 12, I don't know what this warning is about, can we fix the underlying thing it is warning about?

**Comment by jsphuebner** [comment]
I never found the root cause of this warning. In doubt just remove --no-warn-rwx-segments for now

**Comment by davefiddes** [comment]
Looks like it would be complex to get to the bottom of:
https://stackoverflow.com/questions/74765279/custom-linked-binary-has-load-segment-with-rwx-permissions

I would start with bisecting the linker script till the offending section and/or compilation unit can be identified and take it from there.

**Comment by dimecho** [comment]
paste the code into chatGPT and ask it to find it :) chat.openai.com

**Comment by catphish** [comment]
I've had a look, and there are two things in the ELF binary that I find odd:

1) The ROM section is marked as RWX instead of RX. This is what causes the warning, and it seems to be caused by the presence of the .init_array section. I don't understand C++ well enough to know why this section would be considered writable, especially when it's explicitly places in the ROM, which is not writable.

2) The RAM section is marked as RW, but not executable. This is great because it doesn't generate the warning, but it also sort of nonsense because there is definitely executable code copied into RAM.

I'm not certain I'm understanding properly anyway. Linkers are kind of a mystery to me. I think for now we'll have to remove the flag and put up with the warning, but it would be nice if someone who knows better than me (a maintainer of libopencm3?) could assist in tidying this up.

**Comment by jsphuebner** [comment]
What makes you think executable code is copied to RAM?
As for me I can also just ignore the warning. It may be safety critical on PC platforms but certainly isn't in an embedded environment.

**Comment by catphish** [comment]
> What makes you think executable code is copied to RAM?

See this section of code labeled "ramtext"

https://github.com/jsphuebner/libopencm3/blob/5ba1bb5f8b0287a0ccec9def20f3a6185c3a2a8e/lib/cortex-m-generic.ld#L98..L104
https://github.com/libopencm3/libopencm3/blob/504dc95d9ba1c2505a30d575371accfe49a69fb9/lib/stm32/common/flash_common_l01.c#L108..L123

**Comment by catphish** [comment]
It might be worth rebasing against the latest libopencm3 to see if they've solved the problem there, but otherwise I'd say that e2d15c9325a145dc4a12e048ff1ac29a73826fde is a perfectly adequate solution for now, so I'm going to consider this solved.

**Comment by davefiddes** [comment]
I've had a further dig into the root cause of this warning. TLDR: It can be safely ignored or suppressed

The cause of the link warning is global initialisation of C++ objects. These cause the .init_array section to be omitted which for some reason gcc deems this to be writable. The section is just a list of function pointers to initialise so has no need to be writable that I can see or find justification for.

I modified a minimal up to date libopencm3 template application to have a single simple c++ global object and it started emitting the same warning.

Dumping the ELF binary shows more detail:
```
$ readelf -lW stm32_sine

Elf file type is EXEC (Executable file)
Entry point 0x8008cad
There are 2 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x08000000 0x08000000 0x0c398 0x0c398 RWE 0x10000
  LOAD           0x010000 0x20000000 0x0800c398 0x01014 0x013ec RW  0x10000

 Section to Segment mapping:
  Segment Sections...
   00     .text .init_array 
   01     .data .bss 
```

Hacking the linker script to separate the .init_array into a different section eliminates the warning but you can see the new section is RW:

```
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x08000000 0x08000000 0x0c384 0x0c384 R E 0x10000
  LOAD           0x010000 0x20000000 0x0800c384 0x01014 0x013ec RW  0x10000
  LOAD           0x021000 0x09001000 0x09001000 0x00014 0x00014 RW  0x10000

 Section to Segment mapping:
  Segment Sections...
   00     .text 
   01     .data .bss 
   02     .init_array 
```

That table is only read in this loop in the libopencm3 runtime startup:
https://github.com/libopencm3/libopencm3/blob/504dc95d9ba1c2505a30d575371accfe49a69fb9/lib/cm3/vector.c#L88

I found this article a good summary of where we are with bare metal start up and how we got here: https://etherealwake.com/2021/09/crt-startup/

FWIW The .ramtext section is not emitted by the firmware (or bootloader) as the flash_program_half_page() function is not used. This would be visible in the readelf output.

**Comment by catphish** [comment]
@davefiddes thank you for looking into this. Perhaps we should use your modified linker script. I realize this solves nothing except to get rid of the warning, but getting rid of a warning is always an improvement.

**Comment by davefiddes** [comment]
Modifying the linker script would be a very complex and error-prone way to solve the problem. Better to conditionally disable the warning based on the version of GNU ld. Difficult but possible in GNU Make (for example https://github.com/torvalds/linux/blob/b35ad63eeccadbcc83f295a64a029f7e7188444f/scripts/Makefile.compiler#L72).

**Comment by jsphuebner** [comment]
If anyone is able to modify linker script or Makefile without backlash, I'm happy to merge

**Comment by davefiddes** [comment]
Wasn't going to get any peace until I fixed it, so I fixed it. GNU Make is a bin fire tho. Would be much simpler in CMake.
